services:
  telecom-db:
    image: postgres:17-alpine
    container_name: telecom-db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      LANG: ru_RU.utf8
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - telecom_db_data:/var/lib/postgresql/data

volumes:
  telecom_db_data: